config/routes.rb
Spree::Core::Engine.routes.append do
  namespace :admin do
    resources :feedback_reviews
    resources :reviews do
      member do
        get :approve
      end
      resources :feedback_reviews
    end
    resource :review_settings
  end

  resources :products do
    resources :reviews do
      collection do
        get :terms
        get "submissionguidelines"
      end
    end
  end
  match "/reviews/:review_id/feedback(.:format)" => "feedback_reviews#create", :via => :post, :as => "feedback_review"
end

app/models/spree/feedback_review.rb
class Spree::FeedbackReview < ActiveRecord::Base
  belongs_to :review
  belongs_to :user

  validates_presence_of :review_id
  validates_numericality_of :rating, :only_integer => true, :greater_than_or_equal_to => 1, :less_than_or_equal_to => 5, :message => I18n.t('you_must_enter_value_for_rating')

  default_scope order("spree_feedback_reviews.created_at DESC")

end

app/models/spree/product_decorator.rb
# Add access to reviews/ratings to the product model
Spree::Product.class_eval do
  has_many :reviews

  def stars
    avg_rating.round
  end
end

app/models/spree/review.rb
class Spree::Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  has_many   :feedback_reviews

  after_save :recalculate_product_rating, :if => :approved?

  validates_presence_of     :name, :review
  validates_numericality_of :rating, :only_integer => true

  default_scope order("spree_reviews.created_at DESC")

  attr_protected :user_id, :product_id, :ip_address, :approved

  class << self
    def approved
      where(:approved => true)
    end

    def not_approved
      where(:approved => false)
    end

    def approval_filter
      where(["(? = ?) or (approved = ?)", Spree::Reviews::Config[:include_unapproved_reviews], true, true])
    end

    def oldest_first
      order("created_at asc")
    end

    def preview
      limit(Spree::Reviews::Config[:preview_size]).oldest_first
    end
  end

  def feedback_stars
    return 0 if feedback_reviews.count <= 0
    ((feedback_reviews.sum(:rating) / feedback_reviews.count) + 0.5).floor
  end

  def recalculate_product_rating
    reviews_count = product.reviews.reload.approved.count
    if reviews_count > 0
      product.update_attributes(:avg_rating => product.reviews.approved.sum(:rating).to_f / reviews_count, :reviews_count => reviews_count)
    else
      product.update_attribute(:avg_rating, 0)
    end
  end
end

app/models/spree/review_sweeper.rb
class Spree::ReviewSweeper < ActionController::Caching::Sweeper
  observe Spree::Review

  def after_create(review)
    expire_cache_for(review)
  end

  def after_update(review)
    expire_cache_for(review)
  end

  def after_destroy(review)
    expire_cache_for(review)
  end

  private

  def expire_cache_for(review)
    review.product.recalculate_rating
  end
end

app/models/spree/reviews_ability.rb
class Spree::ReviewsAbility
  include CanCan::Ability

  def initialize(user)
    can :create, Spree::Review do |review|
      user.has_role?(:user) || !Spree::Reviews::Config[:require_login]
    end
    can :create, Spree::FeedbackReview do |review|
      user.has_role?(:user) || !Spree::Reviews::Config[:require_login]
    end
  end
end

app/models/spree/reviews_configuration.rb
class Spree::ReviewsConfiguration < Spree::Preferences::Configuration
  # include non-approved reviews in (public) listings
  preference :include_unapproved_reviews, :boolean, :default => false

  # control how many reviews are shown in summaries etc.
  preference :preview_size, :integer, :default => 3

  # show a reviewer's email address
  preference :show_email, :boolean, :default => false

  # show helpfullness rating form elements
  preference :feedback_rating, :boolean, :default => false

  # require login to post reviews
  preference :require_login, :boolean, :default => true
end

app/controllers/spree/admin/feedback_reviews_controller.rb
class Spree::Admin::FeedbackReviewsController <  Spree::Admin::ResourceController
  def index
    @review = Spree::Review.find(params[:review_id])
    @collection = @review.feedback_reviews
  end
end

app/controllers/spree/admin/review_settings_controller.rb
class Spree::Admin::ReviewSettingsController < Spree::Admin::BaseController
  def update
    # workaround for unset checkbox behaviour
    params[:preferences][:include_unapproved_reviews] = false if params[:preferences][:include_unapproved_reviews].blank?
    params[:preferences][:feedback_rating] = false            if params[:preferences][:feedback_rating].blank?
    params[:preferences][:show_email] = false                 if params[:preferences][:show_email].blank?
    params[:preferences][:require_login] = false              if params[:preferences][:require_login].blank?
    Spree::Reviews::Config.set(params[:preferences])

    respond_to do |format|
      format.html do
        redirect_to admin_review_settings_path
      end
    end
  end
end

app/controllers/spree/admin/reviews_controller.rb
class Spree::Admin::ReviewsController < Spree::Admin::ResourceController
  helper Spree::ReviewsHelper

  def index
    @unapproved_reviews = Spree::Review.not_approved.find(:all, :order => "created_at DESC")
    @approved_reviews   = Spree::Review.approved.find(:all, :order => "created_at DESC")
  end

  def approve
    r = Spree::Review.find(params[:id])

    if r.update_attribute(:approved, true)
       flash[:notice] = t("info_approve_review")
    else
       flash[:error] = t("error_approve_review")
    end
    redirect_to admin_reviews_path
  end
end

app/controllers/spree/feedback_reviews_controller.rb
class Spree::FeedbackReviewsController < Spree::BaseController
  helper Spree::BaseHelper

  def create
    params[:feedback_review][:rating].sub!(/\s*stars/,'') unless params[:feedback_review][:rating].blank?

    @review = Spree::Review.find_by_id(params[:review_id])
    if @review && @feedback_review = @review.feedback_reviews.new(params[:feedback_review])
      authorize! :create, @feedback_review
      @feedback_review.save
    end

    respond_to do |format|
      format.html { redirect_to :back  }
      format.js   { render :action => :create }
    end

  end
end

app/controllers/spree/products_controller_decorator.rb
Spree::ProductsController.class_eval do
  helper Spree::ReviewsHelper
end

app/controllers/spree/reviews_controller.rb
class Spree::ReviewsController < Spree::BaseController
  helper Spree::BaseHelper
  before_filter :load_product, :only => [:index, :new, :create]
  rescue_from ActiveRecord::RecordNotFound, :with => :render_404

  def index
    @approved_reviews = Spree::Review.approved.find_all_by_product_id(@product.id)
  end

  def new
    @review = Spree::Review.new(:product => @product)
    authorize! :new, @review
  end

  # save if all ok
  def create
    params[:review][:rating].sub!(/\s*stars/,'') unless params[:review][:rating].blank?

    @review = Spree::Review.new(params[:review])
    @review.product = @product
    @review.user = current_user if user_signed_in?
    @review.ip_address = request.remote_ip

    authorize! :create, @review

    if @review.save
      flash[:notice] = t('review_successfully_submitted')
      redirect_to (product_path(@product))
    else
      render :action => "new"
    end
  end

  def terms
  end

  private

    def load_product
      @product = Spree::Product.find_by_permalink!(params[:product_id])
    end

end

app/helpers/spree/admin/feedback_reviews_helper.rb
module Spree::Admin::FeedbackReviewsHelper
end

app/helpers/spree/feedback_reviews_helper.rb
module Spree::FeedbackReviewsHelper
end

app/helpers/spree/reviews_helper.rb
module Spree::ReviewsHelper

  def star(the_class)
    "<span class=\"#{the_class}\"> &#10030; </span>"
  end

  def mk_stars(m)
    (1..5).collect {|n| n <= m ? star("lit") : star("unlit") }.join
  end

  def txt_stars(n, show_out_of = true)
    res = I18n.t('star', :count => n)
    res += ' ' + t('out_of_5') if show_out_of
    res
  end

end

app/views/spree/admin/feedback_reviews/index.html.erb
<h1><%= link_to t('feedback_review_for', :review => @review.title ), admin_reviews_path %></h1>


<table class="index">
  <tr>
    <th><%= t('date_') %></th>
    <th><%= t('user') %></th>
    <th><%= t('stars') %></th>
    <th></th>
  </tr>
  <% @collection.each do |feedback| %>
    <tr id="<%= dom_id(feedback) %>">
      <td><%= l feedback.created_at %></td>
      <td><%= feedback.user.try(:login) || "anonimus" %></td>
      <td><%= feedback.rating %></td>
      <td class="actions">
        <%= link_to_delete feedback  %>
      </td>
    </tr>
  <% end %>
</table>

app/views/spree/admin/review_settings/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1><%= t("spree_reviews.review_settings") %></h1>

<%= form_tag(admin_review_settings_path, :method => :put) do %>
  <p>
    <label><%= t("spree_reviews.include_unapproved") %>:</label>
    <%= check_box_tag('preferences[include_unapproved_reviews]', "1", Spree::Reviews::Config[:include_unapproved_reviews]) %>
  </p>
  <p>
    <label><%= t("spree_reviews.feedback_rating") %>:</label>
    <%= check_box_tag('preferences[feedback_rating]', "1", Spree::Reviews::Config[:feedback_rating]) %>
  </p>
  <p>
    <label><%= t("spree_reviews.show_email") %>:</label>
    <%= check_box_tag('preferences[show_email]', "1", Spree::Reviews::Config[:show_email]) %>
  </p>
  <p>
    <label><%= t("spree_reviews.require_login") %>:</label>
    <%= check_box_tag('preferences[require_login]', "1", Spree::Reviews::Config[:require_login]) %>
  </p>
  <p>
    <label><%= t('spree_reviews.preview_size') %>:</label>
    <%= text_field_tag('preferences[preview_size]', Spree::Reviews::Config[:preview_size], :size => 3) %>
  </p>
  <p class="form-buttons">
    <%= button t('update') %>
    <%= t("or") %> <%= link_to t("cancel"), admin_review_settings_url %>
  </p>
<% end %>

app/views/spree/admin/review_settings/show.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1><%= t("spree_reviews.review_settings") %></h1>

<table>
  <tr>
    <th scope="row"><%= t("spree_reviews.include_unapproved") %>:</th>
    <td><%= Spree::Reviews::Config[:include_unapproved_reviews] ? t('yes') : t('no') %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("spree_reviews.feedback_rating") %>:</th>
    <td><%= Spree::Reviews::Config[:feedback_rating] ? t('yes') : t('no') %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("spree_reviews.show_email") %>:</th>
    <td><%= Spree::Reviews::Config[:show_email] ? t('yes') : t('no') %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("spree_reviews.require_login") %>:</th>
    <td><%= Spree::Reviews::Config[:require_login] ? t('yes') : t('no') %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("spree_reviews.preview_size") %>:</th>
    <td><%= Spree::Reviews::Config[:preview_size] %></td>
  </tr>
</table>

<p>
  <%= link_to_with_icon('edit', t("edit"), edit_admin_review_settings_path) %>
</p>

app/views/spree/admin/reviews/_form.html.erb
<%= render "spree/shared/error_messages", :target => @review %>
<br />
<p>
  <%= form.text_area :review, :cols => 60, :rows => 10 %>
</p>
<br/>
<p>
  <%= form.submit button_name %>
</p>

app/views/spree/admin/reviews/edit.html.erb
<h1><%= t(:editing_review_for) %> <%= link_to @review.product.name, product_path(@review.product) %></h1>

<h2><%= t(:original_version) %></h2>

<p>
<%= @review.review %>
</p>
<br/>

<h2><%= t(:edited_version) %></h2>

<% form_for([:admin, @review]) do |f| %>
  <%= render :partial => f,
             :locals  => { :button_name => t(:update) } %>
<% end %>

<%= link_to t('back_reviews'), admin_reviews_path %>

app/views/spree/admin/reviews/index.html.erb
<% render 'spree/admin/shared/product_sub_menu' %>
<h1><%= t('review_management_description') %></h1>

<% for reviews in [["Unapproved", @unapproved_reviews], ["Approved", @approved_reviews]] %>
  <h2><%= t(reviews[0]+"_reviews") %></h2>

  <table cellspacing=6 class="index">
    <tr>
      <th><%= Spree::Review.human_attribute_name(:created_at) %></th>
      <th><%= Spree::Review.human_attribute_name(:user) %></th>
      <th><%= Spree::Review.human_attribute_name(:rating) %></th>
      <th><%= Spree::Review.human_attribute_name(:title) %> / <%= t('product') %></th>
      <th><%= Spree::Review.human_attribute_name(:review) %></th>
      <th></th>
    </tr>

    <% for review in reviews[1] %>
    <tr id="<%= dom_id review %>">
      <td>
        <%= l review.created_at, :format => :long %>
      </td>
      <td>
        <p><%= review.name %> / <%= review.user_id ? link_to(review.user.try(:email), [:admin, review.user]) : t(:guest) %></p>
        <p><%= Spree::Review.human_attribute_name(:ip_address) %>: <%= review.ip_address ? link_to(review.ip_address, "http://whois.domaintools.com/#{review.ip_address}") : '-' %></p>
      </td>
      <td>
        <%= txt_stars(review.rating) %>
      </td>
      <td>
        <%= review.title %>
        <% if review.product %>
          <%= t('for') %> <%= link_to review.product.name, product_path(review.product) %>
        <% end %>
      </td>
      <td width="50%">
        <%= h review.review %>
      </td>
      <td>
        <% unless review.approved %>
          <%= link_to_with_icon 'tick', t('approve'), {:action => 'approve', :id => review.id} %> <br />
        <% end %>
        <%= link_to t('feedback'), admin_review_feedback_reviews_path(review) %>(<%= review.feedback_stars %>/<%= review.feedback_reviews.count %>) <br/>
        <%= link_to_edit review %><br/>
        <%= link_to_delete review %>
      </td>
    </tr>
  <% end %>
  </table>
  <br/>
<% end %>

app/views/spree/feedback_reviews/_form.html.erb
<%= render :partial => "spree/feedback_reviews/summary", :locals => {:review => review}%>
<%= form_for((@feedback_review ||= review.feedback_reviews.build), :url => feedback_review_path(review), :method => :post, :remote => true) do |f| %>
<% unless @feedback_review.errors.empty? %>
 <span class="error"><%= @feedback_review.errors[:rating] %></span>
 <br />
<% end %>
<%= t(:was_this_review_helpful) %>
<% for i in 1..NB_STARS %>
<%= radio_button_tag "feedback_review[rating]", pluralize(i, 'stars'), false, :class => "star" %>
<% end %>
<%= hidden_field_tag "feedback_review[user_id]", current_user.try(:id) %>
<button class="feedback-review"><span><%= t("yes") %></span></button>
<% end %>

app/views/spree/feedback_reviews/_summary.html.erb
<p>
  <%= t('voice', :count => review.feedback_reviews.count) %>.
  <span title="<%=pluralize(review.feedback_stars, 'star')%> out of 5">
  <%= render :partial => "spree/reviews/stars", :locals => {:stars => review.feedback_stars} %>
  </span> &nbsp;
</p>

app/views/spree/feedback_reviews/create.js.erb
<% if @feedback_review.valid? %>
$("div#feedback_review_<%= @review.id %>").html("<%= escape_javascript(render(:partial => "spree/feedback_reviews/summary", :locals => {:review => @review})) %>");
<% else %>
$("div#feedback_review_<%= @review.id %>").html("<%= escape_javascript(render(:partial => "spree/feedback_reviews/form", :locals => {:review => @review})) %>");

<% end %>
$(document).ready(function(){$("div#feedback_review_<%= @review.id %>").find(".star").rating({required:true});});

app/views/spree/reviews/_fine_print.html.erb
<div class="review_fine_print">
  <h2><%= t('the_fine_print') %></h2>
  <ul>
    <li><%= t('terms_text') %>: <%= link_to t(:terms_and_conditions), url_for(:action => 'terms') %></li>
    <li><%= t('approved_text') %></li>
    <li><%= t('guideline_text') %>
      : <%= link_to t(:review_guidelines), url_for(:action => 'submissionguidelines') %></li>
  </ul>
</div>

app/views/spree/reviews/_form.html.erb
<%= form_for review, :url => product_reviews_path(product), :html => {:method => :post} do |f| %>
  <%= render "spree/shared/error_messages", :target => review %>

  <p class="review_rating_field">
    <%= f.label :rating %> <span class="required">*</span><br />
    <%= render :partial => "spree/reviews/stars", :locals => {:stars => review.rating, :edit_enabled => true} %>
  </p>

  <p class="review_name_field">
    <%= f.label :name %> <span class="required">*</span><br />
    <%= f.text_field :name, :maxlength => "255", :size => "50" %>
  </p>

  <p class="review_title_field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :maxlength => "255", :size => "50" %>
  </p>
  
  <p class="review_review_field">
    <%= f.label :review %> <span class="required">*</span><br />
    <%= f.text_area :review, :wrap => "virtual", :rows => "10", :cols => "50" %>
  </p>

  <p class="review_submit">
    <%= f.submit I18n.t('submit_your_review'), :class => "button bg_darkfirst" %>
  </p>
<% end %>

app/views/spree/reviews/_stars.html.erb
<% if defined? edit_enabled 
    state = "" 
    name  = "review[rating]" 
  else  
    state = 'disabled="disabled"' 
    name  = defined?(review).nil? ? Time.now.tv_usec.to_s : "review_#{review}" 
  end %>
<% for i in 1..NB_STARS %>
  <input name="<%= name %>" 
         type="radio" class="star" 
         value="<%= pluralize(i, 'stars') %>" <%= state %> 
         <%= "checked=\"checked\"" if i==stars  %> />
<% end %>

app/views/spree/reviews/index.html.erb
<%= render :partial => 'spree/shared/reviews' %>

app/views/spree/reviews/new.html.erb
<h2> <%= I18n.t('leave_us_a_review_for') + ' "' + @product.name + '"' %> </h2>

<%= render 'form', { :review => @review, :product => @product } %>

<%= render :partial => "spree/reviews/fine_print" %>

app/views/spree/reviews/submissionguidelines.html.erb
<h2> <%= t('submission_guidelines') %> </h2>

<p>
Dummy document - expected to be over-ridden in specific instantiations
</p>

app/views/spree/reviews/terms.html.erb
<h2> <%= t('terms_and_conditions') %> </h2>

<p>
Dummy document - expected to be over-ridden in specific instantiations
</p>

app/views/spree/shared/_rating.html.erb
<% stars = product.stars %>
<% reviews_count = product.reviews_count %>
<div class="ratings">
  <p><%= t('average_customer_rating') %>: </p>
  <p>
    <span title="<%= txt_stars(stars) %>">
      <%= render :partial => "spree/reviews/stars", :locals => {:stars => stars} %>
    </span>
  </p>
  <p>(<%= t('based_upon') %> <%= pluralize reviews_count, "review" %>)</p>
  <div itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
    <meta itemprop="ratingValue" content="<%= stars %>" />
    <meta itemprop="reviewCount" content="<%= reviews_count %>" />
  </div>
</div>

app/views/spree/shared/_review.html.erb
<div class="review" itemprop="reviews" itemscope itemtype="http://schema.org/Review">
  <span title="<%= txt_stars(review.rating) %>">
    <%= render :partial => "spree/reviews/stars", :locals => {:stars => review.rating} %>
  </span>
  <meta itemprop="reviewRating" content="<%= review.rating %>" />
  <% if Spree::Reviews::Config[:show_email] && review.user %>
    <span itemprop="author"><%= review.user.email %></span>
  <% else %>
    <span itemprop="author"><%= review.name %></span>
  <% end %>
  <span class="title" itemprop="name">&nbsp; <%= review.title %> </span>
  <br/>
  <span class="attribution"><%= t('submitted_on') %> <strong itemprop="datePublished"><%= l review.created_at.to_date %></strong></span>
  <div itemprop="reviewBody">
    <%= simple_format(review.review) %>
  </div>
  <% if Spree::Reviews::Config[:feedback_rating] && (!Spree::Reviews::Config[:require_login] || current_user) %>
  <div class="feedback_review" id="feedback_review_<%= review.id %>">
    <%= render :partial => "spree/feedback_reviews/form", :locals => {:review => review} %>
  </div>
  <% end %>
</div>

app/views/spree/shared/_review_summary.html.erb
<div id="reviews">
  <%= render :partial => 'spree/shared/rating', :locals => {:product => @product, :review => 0} %>
  <% for review in @product.reviews.approval_filter.preview %>
    <%= render :partial => 'spree/shared/review', :locals => {:review => review} %>
  <% end %>
  <% if Spree::Reviews::Config[:feedback_rating] && (!Spree::Reviews::Config[:require_login] || current_user) %>
    <%= link_to t('write_your_own_review'), new_product_review_path(@product), :class => "button" %>
  <% end %>
</div>

app/views/spree/shared/_reviews.html.erb
<div id="reviews">
  <h6 class="product-section-title"><%= t(:reviews) %></h6>
  <%= render :partial => 'spree/shared/rating', :locals => {:product => @product, :review => 0} %>
  <% for review in @product.reviews.approval_filter %>
    <%= render :partial => 'spree/shared/review', :locals => {:review => review} %>
  <% end %>
  <% if !Spree::Reviews::Config[:require_login] || current_user %>
    <%= link_to t('write_your_own_review'), new_product_review_path(@product), :class => "button",
                :rel => "nofollow,noindex" %>
  <% end %>
</div>

app/views/spree/shared/_shortrating.html.erb
<% stars = product.stars %>
<% reviews_count = product.reviews_count %>
<span style="float:left;" title="<%= txt_stars(stars) %>">
  <%= render :partial => "spree/reviews/stars", :locals => {:stars => stars} %>
</span>
<span style="float:right;">
  <%= Spree::Review.model_name.human(:count => reviews_count) %>
</span>
<br/>